// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example.proto

/*
Package grpc_example is a generated protocol buffer package.

It is generated from these files:
	example.proto

It has these top-level messages:
	Information
*/
package grpc_example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Information struct {
	Description string `protobuf:"bytes,1,opt,name=description" json:"description,omitempty"`
}

func (m *Information) Reset()                    { *m = Information{} }
func (m *Information) String() string            { return proto.CompactTextString(m) }
func (*Information) ProtoMessage()               {}
func (*Information) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Information) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*Information)(nil), "grpc.example.Information")
}

func init() { proto.RegisterFile("example.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 113 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xad, 0x48, 0xcc,
	0x2d, 0xc8, 0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x49, 0x2f, 0x2a, 0x48, 0xd6,
	0x83, 0x8a, 0x49, 0xc9, 0xa4, 0xe7, 0xe7, 0xa7, 0xe7, 0xa4, 0xea, 0x27, 0x16, 0x64, 0xea, 0x27,
	0xe6, 0xe5, 0xe5, 0x97, 0x24, 0x96, 0x64, 0xe6, 0xe7, 0x15, 0x43, 0xd4, 0x2a, 0xe9, 0x73, 0x71,
	0x7b, 0xe6, 0xa5, 0xe5, 0x17, 0xe5, 0x82, 0x45, 0x85, 0x14, 0xb8, 0xb8, 0x53, 0x52, 0x8b, 0x93,
	0x8b, 0x32, 0x0b, 0x40, 0x5c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x64, 0xa1, 0x24, 0x36,
	0xb0, 0x3e, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xee, 0xcd, 0x1b, 0x1c, 0x74, 0x00, 0x00,
	0x00,
}
