apiVersion: v1
kind: Pod
metadata:
  name: nios-pack-migration
  namespace: default
  labels:
    app: nios-pack-migration
spec:
  restartPolicy: Never
  initContainers:
    - name: init-container
#      image: soheileizadi/cmdb-server:latest
      image: narasimhareddy/nios-pack:latest
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: "/nios-pack-migrations"
          name: migrations
      command:
        - "cp"
        - "-r"
        - "/db/migrations"
        - "/nios-pack-migrations"
  containers:
    - name: migration
      env:
        - name: CONFIG_FILE
          value: defaults
      image: infoblox/migrate:latest
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /nios-pack-migrations
          name: migrations
      command:
        - /migrate
      args:
        - "--verbose"
        - "--source"
        - "file:///nios-pack-migrations/migrations"
        - "--database.address"
        - "postgres.contacts:5432"
        - "--database.name"
        - "nios_pack"
        - "--database.user"
        - "postgres"
        - "--database.password"
        - "postgres"
        - up
        # to get to a particular level append following
        - "1"
  volumes:
    - name: migrations
      emptyDir: {}
---
